version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the local backend code into the container
      - ./backend:/app/backend
      # Mount the local database file for persistence
      - ./campaigns.db:/app/campaigns.db
    # Override the Dockerfile CMD to enable hot-reloading
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env

volumes:
  # The database is persistence via a direct file mount in this config
  pass:
